# CMP 262 Project 1

## Fall 2026 Survey Data Cleaning with pandas

**Student name:**  
**Date:**  

### Purpose
In your own words, explain the overall purpose of this notebook and what you are preparing the data for.

## Before You Begin

This notebook is a guide, not a completed solution. Read each section, write your own pandas code in the empty code cells, run the cells, and explain important decisions in Markdown. Do not manually edit the original CSV files.

## 1 Import pandas

Import pandas using the standard alias used in class.

In [45]:
import pandas as pd

## 2 Load the two survey files

Use pandas to read both CSV files from the `data` folder. Store each survey in its own clearly named DataFrame.

Files:
- `Majors Survey Results - Fall 2026.csv`
- `Non-Majors Survey Results - Fall 2026.csv`

In [46]:
majors = pd.read_csv("data/Majors Survey Results - Fall 2026.csv")

In [47]:
non_majors = pd.read_csv("data/Non-Majors Survey Results - Fall 2026.csv")

## 3 Confirm that both files loaded correctly

Display a small number of rows from each DataFrame. Check the number of rows and columns. Write a short observation below the output.

In [48]:
majors.head()

,Timestamp,Which course are you enrolled in?,How did you hear about County College of Morris? [CCM Web site],How did you hear about County College of Morris? [Social Media],How did you hear about County College of Morris? [Community Event],How did you hear about County College of Morris? [Family member or friend],How did you hear about County College of Morris? [Current CCM student],How did you hear about County College of Morris? [CCM Alumni],How did you hear about County College of Morris? [High School Teacher],How did you hear about County College of Morris? [High School Counselor],...,Did you receive information about the CCM computing programs from any of the following sources? [Employer],Did you receive information about the CCM computing programs from any of the following sources? [CCM Workforce Development],Did you receive information about the CCM computing programs from any of the following sources? [NJ Workforce Development Program],Did you receive information about the CCM computing programs from any of the following sources? [Other],"Was a computing major/certificate your first choice, or did you change majors from a different CCM program? If you changed majors, indicate what your first major was.","On a scale of 1 to 5, with 1 being not at all interested and 5 being extremely interested, how interested are you in taking more computing classes?",Please explain your answer to the question above. Why or why not would you be interested in taking another computing class?,Gender,Race/ethnicity,Age
0,2026/09/13 8:33:53 PM AST,CMP 130 Intro to IT,No,No,No,Yes,No,No,Yes,Yes,...,No,No,No,No,First Choice,NaN,NaN,Man,White/Caucasian,18 and younger
1,2026/09/14 4:32:00 AM AST,CMP 130 Intro to IT,No,No,Yes,Yes,No,Yes,No,No,...,No,Yes,Yes,Don't recall,Criminal Sceince,NaN,NaN,Man,White/Caucasian,35-64
2,2026/09/14 9:45:47 AM AST,CMP 130 Intro to IT,Yes,No,Yes,Yes,No,No,Yes,Yes,...,Don't recall,Don't recall,Don't recall,Don't recall,First Choice,NaN,NaN,Man,Multi-Racial,18 and younger
3,2026/09/14 9:47:56 AM AST,CMP 130 Intro to IT,No,No,No,Yes,Yes,No,No,No,...,No,No,No,No,Engineering,NaN,NaN,Man,Hispanic or Latino,21-24
4,2026/09/14 10:00:59 AM AST,CMP 130 Intro to IT,No,No,No,Yes,No,No,No,No,...,No,No,No,No,First Choice,NaN,NaN,Man,White/Caucasian,19-20

In [49]:
non_majors.head()

,Timestamp,Which course are you currently enrolled in?,What motivated you to seek a computing class at CCM? [Itâ€™s a required class for the degree Iâ€™m seeking],What motivated you to seek a computing class at CCM? [To keep current in computing skills],What motivated you to seek a computing class at CCM? [Career Advancement],What motivated you to seek a computing class at CCM? [Career Change],What motivated you to seek a computing class at CCM? [Professional Development],What motivated you to seek a computing class at CCM? [Job Displacement],What motivated you to seek a computing class at CCM? [Relocation],What motivated you to seek a computing class at CCM? [IT Industry Certifications],...,"If you answered that you were interested in taking more computing classes, which ones interest you most? [CyberSecurity]","If you answered that you were interested in taking more computing classes, which ones interest you most? [App Development]","If you answered that you were interested in taking more computing classes, which ones interest you most? [Data Analytics]","If you answered that you were interested in taking more computing classes, which ones interest you most? [Machine Learning/Artificial Intelligence]","If you answered that you were interested in taking more computing classes, which ones interest you most? [Computer Programming]","If you answered that you were interested in taking more computing classes, which ones interest you most? [Game Design]","If you answered that you were interested in taking more computing classes, which ones interest you most? [Hardware Installation & Repair]",Gender,Race/ethnicity,Age
0,2026/09/15 10:07:47 AM AST,CMP 126 Computer Technology and Applications,Yes,No,No,No,No,No,No,No,...,No,No,No,No,No,No,No,Woman,White/Caucasian,18 and younger
1,2026/09/15 2:30:59 PM AST,CMP 126 Computer Technology and Applications,Yes,No,No,No,No,No,No,No,...,No,No,No,No,No,Yes,No,Non-binary,Choose not to reply,18 and younger
2,2026/09/15 6:45:11 PM AST,CMP 126 Computer Technology and Applications,Yes,Yes,No,No,Yes,No,No,No,...,Yes,No,Yes,No,No,No,No,Woman,Asian,19-20
3,2026/09/15 6:59:56 PM AST,CMP 135 Computer Concepts with Applications,Yes,No,No,No,No,No,No,No,...,Yes,No,No,No,No,Yes,No,Woman,Hispanic or Latino,21-24
4,2026/09/15 7:00:28 PM AST,CMP 135 Computer Concepts with Applications,Yes,No,No,No,No,No,No,No,...,No,No,No,No,No,No,No,Man,White/Caucasian,18 and younger

In [50]:
majors.shape

(173, 90)

In [51]:
non_majors.shape

(118, 71)

### Your observation

Write what you learned about the size and general structure of the two datasets.

I learned that both datasets have over 100 entries in them and have 50+ columns of questions for from the students at CCM.

## 4 Explore the datasets

Use separate cells to examine each item below for both DataFrames:

- Column names
- Data types and general information
- Summary statistics where appropriate
- Missing-value counts
- Duplicate rows
- Counts for important categorical columns

Do not place all exploration in one large cell.

In [52]:
majors.info()

<class 'pandas.DataFrame'>
RangeIndex: 173 entries, 0 to 172
Data columns (total 90 columns):
 #   Column                                                                                                                                                                                                                                                           Non-Null Count  Dtype
---  ------                                                                                                                                                                                                                                                           --------------  -----
 0   Timestamp                                                                                                                                                                                                                                                        173 non-null    str
 1   Which course are you enrolled in?                                                                                                                                                                                                                                173 non-null    str
 2   How did you hear about County College of Morris? [CCM Web site]                                                                                                                                                                                                  173 non-null    str
 3   How did you hear about County College of Morris? [Social Media]                                                                                                                                                                                                  173 non-null    str
 4   How did you hear about County College of Morris? [Community Event]                                                                                                                                                                                               173 non-null    str
 5   How did you hear about County College of Morris? [Family member or friend]                                                                                                                                                                                       173 non-null    str
 6   How did you hear about County College of Morris? [Current CCM student]                                                                                                                                                                                           173 non-null    str
 7   How did you hear about County College of Morris? [CCM Alumni]                                                                                                                                                                                                    173 non-null    str
 8   How did you hear about County College of Morris? [High School Teacher]                                                                                                                                                                                           173 non-null    str
 9   How did you hear about County College of Morris? [High School Counselor]                                                                                                                                                                                         173 non-null    str
 10  How did you hear about County College of Morris? [In-app advertisement]                                                                                                                                                                                          173 non-null    str
 11  How did you hear about County College of Morris? [Employer]                                                                                                                                                                                                      173 non-null    str
 12  How did you hear about County College of Morris? [Billboard]                                                                                                                                                                                                     173 non-null    str
 13  How did you hear about County College of Morris? [Television]                                                                                                                                                                                                    173 non-null    str
 14  How did you hear about County College of Morris? [Radio]                                                                                                                                                                                                         173 non-null    str
 15  How did you hear about County College of Morris? [Other]                                                                                                                                                                                                         173 non-null    str
 16  To what extent did the following impact your decision to attend County College of Morris? [Affordable cost]                                                                                                                                                      146 non-null    str
 17  To what extent did the following impact your decision to attend County College of Morris? [Location/convenience]                                                                                                                                                 164 non-null    str
 18  To what extent did the following impact your decision to attend County College of Morris? [Choice of programs]                                                                                                                                                   163 non-null    str
 19  To what extent did the following impact your decision to attend County College of Morris? [Online offerings]                                                                                                                                                     148 non-null    str
 20  To what extent did the following impact your decision to attend County College of Morris? [Family/friend referral]                                                                                                                                               147 non-null    str
 21  To what extent did the following impact your decision to attend County College of Morris? [Faculty/staff]                                                                                                                                                        143 non-null    str
 22  To what extent did the following impact your decision to attend County College of Morris? [College reputation]                                                                                                                                                   151 non-null    str
 23  To what extent did the following impact your decision to attend County College of Morris? [Financial Aid]                                                                                                                                                        137 non-null    str
 24  To what extent did the following impact your decision to attend County College of Morris? [Scholarships]                                                                                                                                                         135 non-null    str
 25  To what extent did the following impact your decision to attend County College of Morris? [Small class sizes]                                                                                                                                                    149 non-null    str
 26  To what extent did the following impact your decision to attend County College of Morris? [Extra-curricular opportunities]                                                                                                                                       146 non-null    str
 27  To what extent did the following impact your decision to attend County College of Morris? [Accepted my transfer credits]                                                                                                                                         125 non-null    str
 28  To what extent did the following impact your decision to attend County College of Morris? [Negative experience at another college]                                                                                                                               113 non-null    str
 29  To what extent did the following impact your decision to attend County College of Morris? [NJ Stars Program]                                                                                                                                                     113 non-null    str
 30  To what extent did the following impact your decision to attend County College of Morris? [Ability to transfer CCM credits to a 4-year school]                                                                                                                   158 non-null    str
 31  To what extent did the following impact your decision to attend County College of Morris? [Get college credit while in high school]                                                                                                                              130 non-null    str
 32  Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Open House]                                                   173 non-null    str
 33  Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Instant Decision Day]                                         173 non-null    str
 34  Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [On-Campus Information Session]                                173 non-null    str
 35  Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Titans Tuesday (Virtual) Information Session]                 173 non-null    str
 36  Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Women Who Dare]                                               173 non-null    str
 37  Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Regional College Fair]                                        173 non-null    str
 38  Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [HS Sharetime Information Session]                             173 non-null    str
 39  Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Challenger Program]                                           173 non-null    str
 40  Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [CyberSecurity Information Protection Program Participation ]  173 non-null    str
 41  Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Information Session at my high school]                        173 non-null    str
 42  Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Campus Visit with my high school]                             173 non-null    str
 43  Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Campus Visit (individual)]                                    173 non-null    str
 44  Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Workforce Development class]                                  173 non-null    str
 45  Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Corporate Training]                                           173 non-null    str
 46  Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Teen Arts Festival]                                           173 non-null    str
 47  Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Summer camp at CCM]                                           173 non-null    str
 48  To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Middle/High school computing class]                                                                                                     143 non-null    str
 49  To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Middle/High school computing related club]                                                                                              125 non-null    str
 50  To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Computing-related competitions (e.g., Robotics competition, Lego competition, Cybersecurity, Programming)]                              131 non-null    str
 51  To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Afterschool computing-related camp/program]                                                                                             120 non-null    str
 52  To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Summer computing related camp/program]                                                                                                  118 non-null    str
 53  To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [An AP computing class]                                                                                                                  121 non-null    str
 54  To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [A dual enrollment computing class]                                                                                                      120 non-null    str
 55  To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Family or friend influence]                                                                                                             143 non-null    str
 56  To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Family or friend working in the computing field]                                                                                        134 non-null    str
 57  To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [High school teacher or guidance counselor]                                                                                              132 non-null    str
 58  To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Employer influence]                                                                                                                     124 non-null    str
 59  To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Current CCM student]                                                                                                                    132 non-null    str
 60  To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Experience at work]                                                                                                                     131 non-null    str
 61  To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Other]                                                                                                                                  112 non-null    str
 62  What degree program are you currently enrolled in?                                                                                                                                                                                                               173 non-null    str
 63  What motivated you to seek a computing degree/certificate at CCM?  [To get a job in the computing field]                                                                                                                                                         114 non-null    str
 64  What motivated you to seek a computing degree/certificate at CCM?  [Transfer to bachelor's level program]                                                                                                                                                        114 non-null    str
 65  What motivated you to seek a computing degree/certificate at CCM?  [Transfer credits back to HS degree (ShareTime, Challenger Program)]                                                                                                                          114 non-null    str
 66  What motivated you to seek a computing degree/certificate at CCM?  [Career Advancement]                                                                                                                                                                          114 non-null    str
 67  What motivated you to seek a computing degree/certificate at CCM?  [Career Change]                                                                                                                                                                               114 non-null    str

In [53]:
non_majors.info()

<class 'pandas.DataFrame'>
RangeIndex: 118 entries, 0 to 117
Data columns (total 71 columns):
 #   Column                                                                                                                                                                                                                                           Non-Null Count  Dtype
---  ------                                                                                                                                                                                                                                           --------------  -----
 0   Timestamp                                                                                                                                                                                                                                        118 non-null    str
 1   Which course are you currently enrolled in?                                                                                                                                                                                                      118 non-null    str
 2   What motivated you to seek a computing class at CCM? [Itâ€™s a required class for the degree Iâ€™m seeking]                                                                                                                                      118 non-null    str
 3   What motivated you to seek a computing class at CCM? [To keep current in computing skills]                                                                                                                                                       118 non-null    str
 4   What motivated you to seek a computing class at CCM? [Career Advancement]                                                                                                                                                                        118 non-null    str
 5   What motivated you to seek a computing class at CCM? [Career Change]                                                                                                                                                                             118 non-null    str
 6   What motivated you to seek a computing class at CCM? [Professional Development]                                                                                                                                                                  118 non-null    str
 7   What motivated you to seek a computing class at CCM? [Job Displacement]                                                                                                                                                                          118 non-null    str
 8   What motivated you to seek a computing class at CCM? [Relocation]                                                                                                                                                                                118 non-null    str
 9   What motivated you to seek a computing class at CCM? [IT Industry Certifications]                                                                                                                                                                118 non-null    str
 10  What motivated you to seek a computing class at CCM? [Financial]                                                                                                                                                                                 118 non-null    str
 11  What motivated you to seek a computing class at CCM? [Personal Enrichment]                                                                                                                                                                       118 non-null    str
 12  What motivated you to seek a computing class at CCM? [Curiosity]                                                                                                                                                                                 118 non-null    str
 13  Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Open House]                                   118 non-null    str
 14  Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Instant Decision Day]                         118 non-null    str
 15  Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [On-Campus Information Session]                118 non-null    str
 16  Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [TItan's Tuesday Virtual Information Session]  118 non-null    str
 17  Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Women Who Dare]                               118 non-null    str
 18  Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Regional College Fair]                        118 non-null    str
 19  To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Middle/High school computing class]                                                                                     97 non-null     str
 20  To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Middle/High school computing related club]                                                                              83 non-null     str
 21  To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Computing-related competitions (e.g., Robotics competition, Lego competition, Cybersecurity, Programming)]              80 non-null     str
 22  To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Afterschool computing-related camp/program]                                                                             79 non-null     str
 23  To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Summer computing related camp/program]                                                                                  79 non-null     str
 24  To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [An AP computing class]                                                                                                  79 non-null     str
 25  To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [A dual enrollment computing class]                                                                                      79 non-null     str
 26  To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Family or friend influence]                                                                                             94 non-null     str
 27  To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Family or friend working in the computing field]                                                                        91 non-null     str
 28  To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [High school teacher or guidance counselor]                                                                              94 non-null     str
 29  To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Employer influence]                                                                                                     92 non-null     str
 30  How did you hear about County College of Morris  [CCM Web site]                                                                                                                                                                                  118 non-null    str
 31  How did you hear about County College of Morris  [Billboard]                                                                                                                                                                                     118 non-null    str
 32  How did you hear about County College of Morris  [Television]                                                                                                                                                                                    118 non-null    str
 33  How did you hear about County College of Morris  [Radio]                                                                                                                                                                                         118 non-null    str
 34  How did you hear about County College of Morris  [Social Media]                                                                                                                                                                                  118 non-null    str
 35  How did you hear about County College of Morris  [Community Event]                                                                                                                                                                               118 non-null    str
 36  How did you hear about County College of Morris  [Family member or friend]                                                                                                                                                                       118 non-null    str
 37  How did you hear about County College of Morris  [Employer]                                                                                                                                                                                      118 non-null    str
 38  How did you hear about County College of Morris  [Current student]                                                                                                                                                                               118 non-null    str
 39  How did you hear about County College of Morris  [Alumni]                                                                                                                                                                                        118 non-null    str
 40  How did you hear about County College of Morris  [High School]                                                                                                                                                                                   118 non-null    str
 41  To what extent did the following impact your decision to attend County College of Morris? [Affordable cost]                                                                                                                                      116 non-null    str
 42  To what extent did the following impact your decision to attend County College of Morris? [Location/convenience]                                                                                                                                 113 non-null    str
 43  To what extent did the following impact your decision to attend County College of Morris? [Choice of programs]                                                                                                                                   108 non-null    str
 44  To what extent did the following impact your decision to attend County College of Morris? [Online offerings]                                                                                                                                     105 non-null    str
 45  To what extent did the following impact your decision to attend County College of Morris? [Family/friend referral]                                                                                                                               101 non-null    str
 46  To what extent did the following impact your decision to attend County College of Morris? [Faculty/staff]                                                                                                                                        97 non-null     str
 47  To what extent did the following impact your decision to attend County College of Morris? [College reputation]                                                                                                                                   107 non-null    str
 48  To what extent did the following impact your decision to attend County College of Morris? [Scholarships]                                                                                                                                         100 non-null    str
 49  To what extent did the following impact your decision to attend County College of Morris? [Transfer student]                                                                                                                                     98 non-null     str
 50  To what extent did the following impact your decision to attend County College of Morris? [Small class sizes]                                                                                                                                    106 non-null    str
 51  To what extent did the following impact your decision to attend County College of Morris? [Extra curricula opportunities]                                                                                                                        102 non-null    str
 52  What degree program are you currently enrolled in?                                                                                                                                                                                               118 non-null    str
 53  Did you receive information about our computing course from any of the following sources? [High school guidance counselor]                                                                                                                       118 non-null    str
 54  Did you receive information about our computing course from any of the following sources? [CCM Information Technologies Website]                                                                                                                 118 non-null    str
 55  Did you receive information about our computing course from any of the following sources? [CCM Admissions]                                                                                                                                       118 non-null    str
 56  Did you receive information about our computing course from any of the following sources? [CCM advisor/counselor]                                                                                                                                118 non-null    str
 57  Did you receive information about our computing course from any of the following sources? [Employer]                                                                                                                                             118 non-null    str
 58  Did you receive information about our computing course from any of the following sources? [Other]                                                                                                                                                118 non-null    str
 59  On a scale of 1 to 5, with 1 being not at all interested and 5 being extremely interested, how interested are you taking more courses in Computer Science, Information Technology or Game Development?                                           118 non-null    int64
 60  If you answered that you were interested in taking more computing classes, which ones interest you most? [Web Development]                                                                                                                       118 non-null    str
 61  If you answered that you were interested in taking more computing classes, which ones interest you most? [CyberSecurity]                                                                                                                         118 non-null    str
 62  If you answered that you were interested in taking more computing classes, which ones interest you most? [App Development]                                                                                                                       118 non-null    str
 63  If you answered that you were interested in taking more computing classes, which ones interest you most? [Data Analytics]                                                                                                                        118 non-null    str
 64  If you answered that you were interested in taking more computing classes, which ones interest you most? [Machine Learning/Artificial Intelligence]                                                                                              118 non-null    str
 65  If you answered that you were interested in taking more computing classes, which ones interest you most? [Computer Programming]                                                                                                                  118 non-null    str
 66  If you answered that you were interested in taking more computing classes, which ones interest you most? [Game Design]                                                                                                                           118 non-null    str
 67  If you answered that you were interested in taking more computing classes, which ones interest you most? [Hardware Installation & Repair]                                                                                                        118 non-null    str
 68  Gender                                                                                                                                                                                                                                           117 non-null    str
 69  Race/ethnicity                                                                                                                                                                                                                                   118 non-null    str
 70  Age                                                                                                                                                                                                                                              118 non-null    str
dtypes: int64(1), str(70)
memory usage: 65.6 KB

In [54]:
majors.describe()

       On a scale of 1 to 5, with 1 being not at all interested and 5 being extremely interested, how interested are you in taking more computing classes?
count                                          59.000000
mean                                            3.322034
std                                             1.151321
min                                             1.000000
25%                                             3.000000
50%                                             3.000000
75%                                             4.000000
max                                             5.000000

In [55]:
non_majors.describe()

       On a scale of 1 to 5, with 1 being not at all interested and 5 being extremely interested, how interested are you taking more courses in Computer Science, Information Technology or Game Development?
count                                         118.000000
mean                                            2.254237
std                                             1.055603
min                                             1.000000
25%                                             1.000000
50%                                             2.000000
75%                                             3.000000
max                                             5.000000

In [56]:
majors[majors.duplicated()]

Empty DataFrame
Columns: [Timestamp, Which course are you enrolled in?, How did you hear about County College of Morris? [CCM Web site], How did you hear about County College of Morris? [Social Media], How did you hear about County College of Morris? [Community Event], How did you hear about County College of Morris? [Family member or friend], How did you hear about County College of Morris? [Current CCM student], How did you hear about County College of Morris? [CCM Alumni], How did you hear about County College of Morris? [High School Teacher], How did you hear about County College of Morris? [High School Counselor], How did you hear about County College of Morris? [In-app advertisement], How did you hear about County College of Morris? [Employer], How did you hear about County College of Morris? [Billboard], How did you hear about County College of Morris? [Television], How did you hear about County College of Morris? [Radio], How did you hear about County College of Morris? [Other], To what extent did the following impact your decision to attend County College of Morris? [Affordable cost], To what extent did the following impact your decision to attend County College of Morris? [Location/convenience], To what extent did the following impact your decision to attend County College of Morris? [Choice of programs], To what extent did the following impact your decision to attend County College of Morris? [Online offerings], To what extent did the following impact your decision to attend County College of Morris? [Family/friend referral], To what extent did the following impact your decision to attend County College of Morris? [Faculty/staff], To what extent did the following impact your decision to attend County College of Morris? [College reputation], To what extent did the following impact your decision to attend County College of Morris? [Financial Aid], To what extent did the following impact your decision to attend County College of Morris? [Scholarships], To what extent did the following impact your decision to attend County College of Morris? [Small class sizes], To what extent did the following impact your decision to attend County College of Morris? [Extra-curricular opportunities], To what extent did the following impact your decision to attend County College of Morris? [Accepted my transfer credits], To what extent did the following impact your decision to attend County College of Morris? [Negative experience at another college], To what extent did the following impact your decision to attend County College of Morris? [NJ Stars Program], To what extent did the following impact your decision to attend County College of Morris? [Ability to transfer CCM credits to a 4-year school], To what extent did the following impact your decision to attend County College of Morris? [Get college credit while in high school], Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Open House], Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Instant Decision Day], Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [On-Campus Information Session], Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Titans Tuesday (Virtual) Information Session], Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Women Who Dare], Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Regional College Fair], Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [HS Sharetime Information Session], Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Challenger Program], Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [CyberSecurity Information Protection Program Participation ], Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Information Session at my high school], Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Campus Visit with my high school], Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Campus Visit (individual)], Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Workforce Development class], Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Corporate Training], Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Teen Arts Festival], Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Summer camp at CCM], To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Middle/High school computing class], To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Middle/High school computing related club], To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Computing-related competitions (e.g., Robotics competition, Lego competition, Cybersecurity, Programming)], To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Afterschool computing-related camp/program], To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Summer computing related camp/program], To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [An AP computing class], To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [A dual enrollment computing class], To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Family or friend influence], To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Family or friend working in the computing field], To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [High school teacher or guidance counselor], To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Employer influence], To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Current CCM student], To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Experience at work], To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Other], What degree program are you currently enrolled in?, What motivated you to seek a computing degree/certificate at CCM?  [To get a job in the computing field], What motivated you to seek a computing degree/certificate at CCM?  [Transfer to bachelor's level program], What motivated you to seek a computing degree/certificate at CCM?  [Transfer credits back to HS degree (ShareTime, Challenger Program)], What motivated you to seek a computing degree/certificate at CCM?  [Career Advancement], What motivated you to seek a computing degree/certificate at CCM?  [Career Change], What motivated you to seek a computing degree/certificate at CCM?  [Professional Development], What motivated you to seek a computing degree/certificate at CCM?  [Job Displacement], What motivated you to seek a computing degree/certificate at CCM?  [Relocation], What motivated you to seek a computing degree/certificate at CCM?  [To keep current in tech industry], What motivated you to seek a computing degree/certificate at CCM?  [IT Industry Certifications], What motivated you to seek a computing degree/certificate at CCM?  [Financial], What motivated you to seek a computing degree/certificate at CCM?  [Personal Enrichment], Did you receive information about the CCM computing programs from any of the following sources? [High school guidance counselor], Did you receive information about the CCM computing programs from any of the following sources? [High School Teacher], Did you receive information about the CCM computing programs from any of the following sources? [CCM Information Technologies Website], Did you receive information about the CCM computing programs from any of the following sources? [CCM Admissions], Did you receive information about the CCM computing programs from any of the following sources? [CCM advisor/counselor], Did you receive information about the CCM computing programs from any of the following sources? [Employer], Did you receive information about the CCM computing programs from any of the following sources? [CCM Workforce Development], Did you receive information about the CCM computing programs from any of the following sources? [NJ Workforce Development Program], Did you receive information about the CCM computing programs from any of the following sources? [Other], Was a computing major/certificate your first choice, or did you change majors from a different CCM program? If you changed majors, indicate what your first major was., On a scale of 1 to 5, with 1 being not at all interested and 5 being extremely interested, how interested are you in taking more computing classes?, Please explain your answer to the question above.  Why or why not would you be interested in taking another computing class?, Gender, Race/ethnicity, Age ]
Index: []

[0 rows x 90 columns]

In [57]:
non_majors.duplicated().sum()

np.int64(0)

### Exploration findings

Describe at least three important issues or patterns you discovered.

## 5 Clean the column names

Rename the columns so they are clear, lowercase, and use underscores between words when needed. Make sure the final column names are unique.

Show the column names before and after cleaning.

In [58]:
majors.rename(columns={
    'Timestamp': 'timestamp',
    'Which course are you enrolled in?': 'which_course_are_you_enrolled_in?',
    'How did you hear about County College of Morris? [CCM Web site]': 'how_did_you_hear_about_county_college_of_morris?_[ccm_web_site]',
    'How did you hear about County College of Morris? [Social Media]': 'how_did_you_hear_about_county_college_of_morris?_[social_media]',
    'How did you hear about County College of Morris? [Community Event]': 'how_did_you_hear_about_county_college_of_morris?_[community_event]',
    'How did you hear about County College of Morris? [Family member or friend]': 'how_did_you_hear_about_county_college_of_morris?_[family_member_or_friend]',
    'How did you hear about County College of Morris? [Current CCM student]': 'how_did_you_hear_about_county_college_of_morris?_[current_ccm_student]',
    'How did you hear about County College of Morris? [CCM Alumni]': 'how_did_you_hear_about_county_college_of_morris?_[ccm_alumni]',
    'How did you hear about County College of Morris? [High School Teacher]': 'how_did_you_hear_about_county_college_of_morris?_[high_school_teacher]',
    'How did you hear about County College of Morris? [High School Counselor]': 'how_did_you_hear_about_county_college_of_morris?_[high_school_counselor]',
    'How did you hear about County College of Morris? [In-app advertisement]': 'how_did_you_hear_about_county_college_of_morris?_[in-app_advertisement]',
    'How did you hear about County College of Morris? [Employer]': 'how_did_you_hear_about_county_college_of_morris?_[employer]',
    'How did you hear about County College of Morris? [Billboard]': 'how_did_you_hear_about_county_college_of_morris?_[billboard]',
    'How did you hear about County College of Morris? [Television]': 'how_did_you_hear_about_county_college_of_morris?_[television]',
    'How did you hear about County College of Morris? [Radio]': 'how_did_you_hear_about_county_college_of_morris?_[radio]',
    'How did you hear about County College of Morris? [Other]': 'how_did_you_hear_about_county_college_of_morris?_[other]',
    'To what extent did the following impact your decision to attend County College of Morris? [Affordable cost]': 'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[affordable_cost]',
    'To what extent did the following impact your decision to attend County College of Morris? [Location/convenience]': 'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[location/convenience]',
    'To what extent did the following impact your decision to attend County College of Morris? [Choice of programs]': 'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[choice_of_programs]',
    'To what extent did the following impact your decision to attend County College of Morris? [Online offerings]': 'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[online_offerings]',
    'To what extent did the following impact your decision to attend County College of Morris? [Family/friend referral]': 'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[family/friend_referral]',
    'To what extent did the following impact your decision to attend County College of Morris? [Faculty/staff]': 'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[faculty/staff]',
    'To what extent did the following impact your decision to attend County College of Morris? [College reputation]': 'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[college_reputation]',
    'To what extent did the following impact your decision to attend County College of Morris? [Financial Aid]': 'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[financial_aid]',
    'To what extent did the following impact your decision to attend County College of Morris? [Scholarships]': 'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[scholarships]',
    'To what extent did the following impact your decision to attend County College of Morris? [Small class sizes]': 'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[small_class_sizes]',
    'To what extent did the following impact your decision to attend County College of Morris? [Extra-curricular opportunities]': 'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[extra-curricular_opportunities]',
    'To what extent did the following impact your decision to attend County College of Morris? [Accepted my transfer credits]': 'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[accepted_my_transfer_credits]',
    'To what extent did the following impact your decision to attend County College of Morris? [Negative experience at another college]': 'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[negative_experience_at_another_college]',
    'To what extent did the following impact your decision to attend County College of Morris? [NJ Stars Program]': 'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[nj_stars_program]',
    'To what extent did the following impact your decision to attend County College of Morris? [Ability to transfer CCM credits to a 4-year school]': 'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[ability_to_transfer_ccm_credits_to_a_4-year_school]',
    'To what extent did the following impact your decision to attend County College of Morris? [Get college credit while in high school]': 'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[get_college_credit_while_in_high_school]',
    'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Open House]': 'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[open_house]',
    'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Instant Decision Day]': 'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[instant_decision_day]',
    'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [On-Campus Information Session]': 'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[on-campus_information_session]',
    'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Titans Tuesday (Virtual) Information Session]': 'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[titans_tuesday_(virtual)_information_session]',
    'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Women Who Dare]': 'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[women_who_dare]',
    'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Regional College Fair]': 'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[regional_college_fair]',
    'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [HS Sharetime Information Session]': 'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[hs_sharetime_information_session]',
    'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Challenger Program]': 'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[challenger_program]',
    'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [CyberSecurity Information Protection Program Participation ]': 'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[cybersecurity_information_protection_program_participation_]',
    'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Information Session at my high school]': 'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[information_session_at_my_high_school]',
    'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Campus Visit with my high school]': 'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[campus_visit_with_my_high_school]',
    'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Campus Visit (individual)]': 'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[campus_visit_(individual)]',
    'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Workforce Development class]': 'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[workforce_development_class]',
    'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Corporate Training]': 'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[corporate_training]',
    'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Teen Arts Festival]': 'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[teen_arts_festival]',
    'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Summer camp at CCM]': 'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[summer_camp_at_ccm]',
    'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Middle/High school computing class]': 'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[middle/high_school_computing_class]',
    'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Middle/High school computing related club]': 'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[middle/high_school_computing_related_club]',
    'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Computing-related competitions (e.g., Robotics competition, Lego competition, Cybersecurity, Programming)]': 'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[computing-related_competitions_(e.g.,_robotics_competition,_lego_competition,_cybersecurity,_programming)]',
    'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Afterschool computing-related camp/program]': 'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[afterschool_computing-related_camp/program]',
    'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Summer computing related camp/program]': 'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[summer_computing_related_camp/program]',
    'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [An AP computing class]': 'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[an_ap_computing_class]',
    'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [A dual enrollment computing class]': 'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[a_dual_enrollment_computing_class]',
    'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Family or friend influence]': 'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[family_or_friend_influence]',
    'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Family or friend working in the computing field]': 'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[family_or_friend_working_in_the_computing_field]',
    'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [High school teacher or guidance counselor]': 'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[high_school_teacher_or_guidance_counselor]',
    'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Employer influence]': 'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[employer_influence]',
    'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Current CCM student]': 'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[current_ccm_student]',
    'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Experience at work]': 'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[experience_at_work]',
    'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Other]': 'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[other]',
    'What degree program are you currently enrolled in?': 'what_degree_program_are_you_currently_enrolled_in?',
    'What motivated you to seek a computing degree/certificate at CCM?  [To get a job in the computing field]': 'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[to_get_a_job_in_the_computing_field]',
    "What motivated you to seek a computing degree/certificate at CCM?  [Transfer to bachelor's level program]": "what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[transfer_to_bachelor's_level_program]",
    'What motivated you to seek a computing degree/certificate at CCM?  [Transfer credits back to HS degree (ShareTime, Challenger Program)]': 'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[transfer_credits_back_to_hs_degree_(sharetime,_challenger_program)]',
    'What motivated you to seek a computing degree/certificate at CCM?  [Career Advancement]': 'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[career_advancement]',
    'What motivated you to seek a computing degree/certificate at CCM?  [Career Change]': 'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[career_change]',
    'What motivated you to seek a computing degree/certificate at CCM?  [Professional Development]': 'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[professional_development]',
    'What motivated you to seek a computing degree/certificate at CCM?  [Job Displacement]': 'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[job_displacement]',
    'What motivated you to seek a computing degree/certificate at CCM?  [Relocation]': 'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[relocation]',
    'What motivated you to seek a computing degree/certificate at CCM?  [To keep current in tech industry]': 'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[to_keep_current_in_tech_industry]',
    'What motivated you to seek a computing degree/certificate at CCM?  [IT Industry Certifications]': 'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[it_industry_certifications]',
    'What motivated you to seek a computing degree/certificate at CCM?  [Financial]': 'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[financial]',
    'What motivated you to seek a computing degree/certificate at CCM?  [Personal Enrichment]': 'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[personal_enrichment]',
    'Did you receive information about the CCM computing programs from any of the following sources? [High school guidance counselor]': 'did_you_receive_information_about_the_ccm_computing_programs_from_any_of_the_following_sources?_[high_school_guidance_counselor]',
    'Did you receive information about the CCM computing programs from any of the following sources? [High School Teacher]': 'did_you_receive_information_about_the_ccm_computing_programs_from_any_of_the_following_sources?_[high_school_teacher]',
    'Did you receive information about the CCM computing programs from any of the following sources? [CCM Information Technologies Website]': 'did_you_receive_information_about_the_ccm_computing_programs_from_any_of_the_following_sources?_[ccm_information_technologies_website]',
    'Did you receive information about the CCM computing programs from any of the following sources? [CCM Admissions]': 'did_you_receive_information_about_the_ccm_computing_programs_from_any_of_the_following_sources?_[ccm_admissions]',
    'Did you receive information about the CCM computing programs from any of the following sources? [CCM advisor/counselor]': 'did_you_receive_information_about_the_ccm_computing_programs_from_any_of_the_following_sources?_[ccm_advisor/counselor]',
    'Did you receive information about the CCM computing programs from any of the following sources? [Employer]': 'did_you_receive_information_about_the_ccm_computing_programs_from_any_of_the_following_sources?_[employer]',
    'Did you receive information about the CCM computing programs from any of the following sources? [CCM Workforce Development]': 'did_you_receive_information_about_the_ccm_computing_programs_from_any_of_the_following_sources?_[ccm_workforce_development]',
    'Did you receive information about the CCM computing programs from any of the following sources? [NJ Workforce Development Program]': 'did_you_receive_information_about_the_ccm_computing_programs_from_any_of_the_following_sources?_[nj_workforce_development_program]',
    'Did you receive information about the CCM computing programs from any of the following sources? [Other]': 'did_you_receive_information_about_the_ccm_computing_programs_from_any_of_the_following_sources?_[other]',
    'Was a computing major/certificate your first choice, or did you change majors from a different CCM program? If you changed majors, indicate what your first major was.': 'was_a_computing_major/certificate_your_first_choice,_or_did_you_change_majors_from_a_different_ccm_program?_if_you_changed_majors,_indicate_what_your_first_major_was.',
    'On a scale of 1 to 5, with 1 being not at all interested and 5 being extremely interested, how interested are you in taking more computing classes?': 'on_a_scale_of_1_to_5,_with_1_being_not_at_all_interested_and_5_being_extremely_interested,_how_interested_are_you_in_taking_more_computing_classes?',
    'Please explain your answer to the question above.  Why or why not would you be interested in taking another computing class?': 'please_explain_your_answer_to_the_question_above.__why_or_why_not_would_you_be_interested_in_taking_another_computing_class?',
    'Gender': 'gender',
    'Race/ethnicity': 'race/ethnicity',
    'Age': 'age',
}, inplace=True)

In [59]:
non_majors.rename(columns={
        'Timestamp': 'timestamp',
    'Which course are you currently enrolled in?': 'which_course_are_you_currently_enrolled_in?',
    'What motivated you to seek a computing class at CCM? [Itâ€™s a required class for the degree Iâ€™m seeking]': 'what_motivated_you_to_seek_a_computing_class_at_ccm?_[itâ€™s_a_required_class_for_the_degree_iâ€™m_seeking]',
    'What motivated you to seek a computing class at CCM? [To keep current in computing skills]': 'what_motivated_you_to_seek_a_computing_class_at_ccm?_[to_keep_current_in_computing_skills]',
    'What motivated you to seek a computing class at CCM? [Career Advancement]': 'what_motivated_you_to_seek_a_computing_class_at_ccm?_[career_advancement]',
    'What motivated you to seek a computing class at CCM? [Career Change]': 'what_motivated_you_to_seek_a_computing_class_at_ccm?_[career_change]',
    'What motivated you to seek a computing class at CCM? [Professional Development]': 'what_motivated_you_to_seek_a_computing_class_at_ccm?_[professional_development]',
    'What motivated you to seek a computing class at CCM? [Job Displacement]': 'what_motivated_you_to_seek_a_computing_class_at_ccm?_[job_displacement]',
    'What motivated you to seek a computing class at CCM? [Relocation]': 'what_motivated_you_to_seek_a_computing_class_at_ccm?_[relocation]',
    'What motivated you to seek a computing class at CCM? [IT Industry Certifications]': 'what_motivated_you_to_seek_a_computing_class_at_ccm?_[it_industry_certifications]',
    'What motivated you to seek a computing class at CCM? [Financial]': 'what_motivated_you_to_seek_a_computing_class_at_ccm?_[financial]',
    'What motivated you to seek a computing class at CCM? [Personal Enrichment]': 'what_motivated_you_to_seek_a_computing_class_at_ccm?_[personal_enrichment]',
    'What motivated you to seek a computing class at CCM? [Curiosity]': 'what_motivated_you_to_seek_a_computing_class_at_ccm?_[curiosity]',
    'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Open House]': 'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[open_house]',
    'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Instant Decision Day]': 'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[instant_decision_day]',
    'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [On-Campus Information Session]': 'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[on-campus_information_session]',
    "Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [TItan's Tuesday Virtual Information Session]": "prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[titan's_tuesday_virtual_information_session]",
    'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Women Who Dare]': 'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[women_who_dare]',
    'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Regional College Fair]': 'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[regional_college_fair]',
    'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Middle/High school computing class]': 'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[middle/high_school_computing_class]',
    'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Middle/High school computing related club]': 'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[middle/high_school_computing_related_club]',
    'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Computing-related competitions (e.g., Robotics competition, Lego competition, Cybersecurity, Programming)]': 'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[computing-related_competitions_(e.g.,_robotics_competition,_lego_competition,_cybersecurity,_programming)]',
    'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Afterschool computing-related camp/program]': 'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[afterschool_computing-related_camp/program]',
    'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Summer computing related camp/program]': 'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[summer_computing_related_camp/program]',
    'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [An AP computing class]': 'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[an_ap_computing_class]',
    'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [A dual enrollment computing class]': 'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[a_dual_enrollment_computing_class]',
    'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Family or friend influence]': 'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[family_or_friend_influence]',
    'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Family or friend working in the computing field]': 'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[family_or_friend_working_in_the_computing_field]',
    'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [High school teacher or guidance counselor]': 'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[high_school_teacher_or_guidance_counselor]',
    'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Employer influence]': 'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[employer_influence]',
    'How did you hear about County College of Morris  [CCM Web site]': 'how_did_you_hear_about_county_college_of_morris__[ccm_web_site]',
    'How did you hear about County College of Morris  [Billboard]': 'how_did_you_hear_about_county_college_of_morris__[billboard]',
    'How did you hear about County College of Morris  [Television]': 'how_did_you_hear_about_county_college_of_morris__[television]',
    'How did you hear about County College of Morris  [Radio]': 'how_did_you_hear_about_county_college_of_morris__[radio]',
    'How did you hear about County College of Morris  [Social Media]': 'how_did_you_hear_about_county_college_of_morris__[social_media]',
    'How did you hear about County College of Morris  [Community Event]': 'how_did_you_hear_about_county_college_of_morris__[community_event]',
    'How did you hear about County College of Morris  [Family member or friend]': 'how_did_you_hear_about_county_college_of_morris__[family_member_or_friend]',
    'How did you hear about County College of Morris  [Employer]': 'how_did_you_hear_about_county_college_of_morris__[employer]',
    'How did you hear about County College of Morris  [Current student]': 'how_did_you_hear_about_county_college_of_morris__[current_student]',
    'How did you hear about County College of Morris  [Alumni]': 'how_did_you_hear_about_county_college_of_morris__[alumni]',
    'How did you hear about County College of Morris  [High School]': 'how_did_you_hear_about_county_college_of_morris__[high_school]',
    'To what extent did the following impact your decision to attend County College of Morris? [Affordable cost]': 'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[affordable_cost]',
    'To what extent did the following impact your decision to attend County College of Morris? [Location/convenience]': 'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[location/convenience]',
    'To what extent did the following impact your decision to attend County College of Morris? [Choice of programs]': 'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[choice_of_programs]',
    'To what extent did the following impact your decision to attend County College of Morris? [Online offerings]': 'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[online_offerings]',
    'To what extent did the following impact your decision to attend County College of Morris? [Family/friend referral]': 'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[family/friend_referral]',
    'To what extent did the following impact your decision to attend County College of Morris? [Faculty/staff]': 'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[faculty/staff]',
    'To what extent did the following impact your decision to attend County College of Morris? [College reputation]': 'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[college_reputation]',
    'To what extent did the following impact your decision to attend County College of Morris? [Scholarships]': 'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[scholarships]',
    'To what extent did the following impact your decision to attend County College of Morris? [Transfer student]': 'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[transfer_student]',
    'To what extent did the following impact your decision to attend County College of Morris? [Small class sizes]': 'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[small_class_sizes]',
    'To what extent did the following impact your decision to attend County College of Morris? [Extra curricula opportunities]': 'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[extra_curricula_opportunities]',
    'What degree program are you currently enrolled in?': 'what_degree_program_are_you_currently_enrolled_in?',
    'Did you receive information about our computing course from any of the following sources? [High school guidance counselor]': 'did_you_receive_information_about_our_computing_course_from_any_of_the_following_sources?_[high_school_guidance_counselor]',
    'Did you receive information about our computing course from any of the following sources? [CCM Information Technologies Website]': 'did_you_receive_information_about_our_computing_course_from_any_of_the_following_sources?_[ccm_information_technologies_website]',
    'Did you receive information about our computing course from any of the following sources? [CCM Admissions]': 'did_you_receive_information_about_our_computing_course_from_any_of_the_following_sources?_[ccm_admissions]',
    'Did you receive information about our computing course from any of the following sources? [CCM advisor/counselor]': 'did_you_receive_information_about_our_computing_course_from_any_of_the_following_sources?_[ccm_advisor/counselor]',
    'Did you receive information about our computing course from any of the following sources? [Employer]': 'did_you_receive_information_about_our_computing_course_from_any_of_the_following_sources?_[employer]',
    'Did you receive information about our computing course from any of the following sources? [Other]': 'did_you_receive_information_about_our_computing_course_from_any_of_the_following_sources?_[other]',
    'On a scale of 1 to 5, with 1 being not at all interested and 5 being extremely interested, how interested are you taking more courses in Computer Science, Information Technology or Game Development?': 'on_a_scale_of_1_to_5,_with_1_being_not_at_all_interested_and_5_being_extremely_interested,_how_interested_are_you_taking_more_courses_in_computer_science,_information_technology_or_game_development?',
    'If you answered that you were interested in taking more computing classes, which ones interest you most? [Web Development]': 'if_you_answered_that_you_were_interested_in_taking_more_computing_classes,_which_ones_interest_you_most?_[web_development]',
    'If you answered that you were interested in taking more computing classes, which ones interest you most? [CyberSecurity]': 'if_you_answered_that_you_were_interested_in_taking_more_computing_classes,_which_ones_interest_you_most?_[cybersecurity]',
    'If you answered that you were interested in taking more computing classes, which ones interest you most? [App Development]': 'if_you_answered_that_you_were_interested_in_taking_more_computing_classes,_which_ones_interest_you_most?_[app_development]',
    'If you answered that you were interested in taking more computing classes, which ones interest you most? [Data Analytics]': 'if_you_answered_that_you_were_interested_in_taking_more_computing_classes,_which_ones_interest_you_most?_[data_analytics]',
    'If you answered that you were interested in taking more computing classes, which ones interest you most? [Machine Learning/Artificial Intelligence]': 'if_you_answered_that_you_were_interested_in_taking_more_computing_classes,_which_ones_interest_you_most?_[machine_learning/artificial_intelligence]',
    'If you answered that you were interested in taking more computing classes, which ones interest you most? [Computer Programming]': 'if_you_answered_that_you_were_interested_in_taking_more_computing_classes,_which_ones_interest_you_most?_[computer_programming]',
    'If you answered that you were interested in taking more computing classes, which ones interest you most? [Game Design]': 'if_you_answered_that_you_were_interested_in_taking_more_computing_classes,_which_ones_interest_you_most?_[game_design]',
    'If you answered that you were interested in taking more computing classes, which ones interest you most? [Hardware Installation & Repair]': 'if_you_answered_that_you_were_interested_in_taking_more_computing_classes,_which_ones_interest_you_most?_[hardware_installation_&_repair]',
    'Gender': 'gender',
    'Race/ethnicity': 'race/ethnicity',
    'Age': 'age',
}, inplace=True)

### Column-name decisions

Explain the method you used and describe any columns that required special attention.

I manually renamed all the columns in a dictionary.

## 6 Select useful features

The study focuses on recruitment and enrollment. Decide which columns are useful for that purpose and which are irrelevant or redundant.

Before removing anything:
1. List the columns you plan to keep or remove.
2. Explain your reasoning.
3. Use pandas to create cleaned DataFrames without changing the original DataFrames.

### Feature-selection plan

Write your plan and justification here before writing the code.

I would like to remove the race/ethnicity and gender columns since they are not directly related to the study.

In [60]:
majors_clean = majors.copy()
non_majors_clean = non_majors.copy()

In [61]:
majors_clean = majors_clean.drop(columns=["race/ethnicity", "gender"])

In [62]:
non_majors_clean = non_majors_clean.drop(columns=["race/ethnicity", "gender"])

In [63]:
print(majors_clean.columns)
print(non_majors_clean.columns)

Index(['timestamp', 'which_course_are_you_enrolled_in?',
       'how_did_you_hear_about_county_college_of_morris?_[ccm_web_site]',
       'how_did_you_hear_about_county_college_of_morris?_[social_media]',
       'how_did_you_hear_about_county_college_of_morris?_[community_event]',
       'how_did_you_hear_about_county_college_of_morris?_[family_member_or_friend]',
       'how_did_you_hear_about_county_college_of_morris?_[current_ccm_student]',
       'how_did_you_hear_about_county_college_of_morris?_[ccm_alumni]',
       'how_did_you_hear_about_county_college_of_morris?_[high_school_teacher]',
       'how_did_you_hear_about_county_college_of_morris?_[high_school_counselor]',
       'how_did_you_hear_about_county_college_of_morris?_[in-app_advertisement]',
       'how_did_you_hear_about_county_college_of_morris?_[employer]',
       'how_did_you_hear_about_county_college_of_morris?_[billboard]',
       'how_did_you_hear_about_county_college_of_morris?_[television]',
       'how_did_you_hear_about_county_college_of_morris?_[radio]',
       'how_did_you_hear_about_county_college_of_morris?_[other]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[affordable_cost]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[location/convenience]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[choice_of_programs]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[online_offerings]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[family/friend_referral]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[faculty/staff]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[college_reputation]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[financial_aid]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[scholarships]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[small_class_sizes]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[extra-curricular_opportunities]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[accepted_my_transfer_credits]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[negative_experience_at_another_college]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[nj_stars_program]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[ability_to_transfer_ccm_credits_to_a_4-year_school]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[get_college_credit_while_in_high_school]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[open_house]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[instant_decision_day]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[on-campus_information_session]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[titans_tuesday_(virtual)_information_session]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[women_who_dare]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[regional_college_fair]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[hs_sharetime_information_session]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[challenger_program]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[cybersecurity_information_protection_program_participation_]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[information_session_at_my_high_school]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[campus_visit_with_my_high_school]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[campus_visit_(individual)]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[workforce_development_class]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[corporate_training]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[teen_arts_festival]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[summer_camp_at_ccm]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[middle/high_school_computing_class]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[middle/high_school_computing_related_club]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[computing-related_competitions_(e.g.,_robotics_competition,_lego_competition,_cybersecurity,_programming)]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[afterschool_computing-related_camp/program]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[summer_computing_related_camp/program]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[an_ap_computing_class]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[a_dual_enrollment_computing_class]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[family_or_friend_influence]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[family_or_friend_working_in_the_computing_field]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[high_school_teacher_or_guidance_counselor]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[employer_influence]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[current_ccm_student]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[experience_at_work]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[other]',
       'what_degree_program_are_you_currently_enrolled_in?',
       'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[to_get_a_job_in_the_computing_field]',
       'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[transfer_to_bachelor's_level_program]',
       'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[transfer_credits_back_to_hs_degree_(sharetime,_challenger_program)]',
       'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[career_advancement]',
       'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[career_change]',
       'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[professional_development]',
       'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[job_displacement]',
       'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[relocation]',
       'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[to_keep_current_in_tech_industry]',
       'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[it_industry_certifications]',
       'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[financial]',
       'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[personal_enrichment]',
       'did_you_receive_information_about_the_ccm_computing_programs_from_any_of_the_following_sources?_[high_school_guidance_counselor]',
       'did_you_receive_information_about_the_ccm_computing_programs_from_any_of_the_following_sources?_[high_school_teacher]',
       'did_you_receive_information_about_the_ccm_computing_programs_from_any_of_the_following_sources?_[ccm_information_technologies_website]',
       'did_you_receive_information_about_the_ccm_computing_programs_from_any_of_the_following_sources?_[ccm_admissions]',
       'did_you_receive_information_about_the_ccm_computing_programs_from_any_of_the_following_sources?_[ccm_advisor/counselor]',
       'did_you_receive_information_about_the_ccm_computing_programs_from_any_of_the_following_sources?_[employer]',
       'did_you_receive_information_about_the_ccm_computing_programs_from_any_of_the_following_sources?_[ccm_workforce_development]',
       'did_you_receive_information_about_the_ccm_computing_programs_from_any_of_the_following_sources?_[nj_workforce_development_program]',
       'did_you_receive_information_about_the_ccm_computing_programs_from_any_of_the_following_sources?_[other]',
       'was_a_computing_major/certificate_your_first_choice,_or_did_you_change_majors_from_a_different_ccm_program?_if_you_changed_majors,_indicate_what_your_first_major_was.',
       'on_a_scale_of_1_to_5,_with_1_being_not_at_all_interested_and_5_being_extremely_interested,_how_interested_are_you_in_taking_more_computing_classes?',
       'please_explain_your_answer_to_the_question_above.__why_or_why_not_would_you_be_interested_in_taking_another_computing_class?',
       'Age '],
      dtype='str')
Index(['timestamp', 'which_course_are_you_currently_enrolled_in?',
       'what_motivated_you_to_seek_a_computing_class_at_ccm?_[itâ€™s_a_required_class_for_the_degree_iâ€™m_seeking]',
       'what_motivated_you_to_seek_a_computing_class_at_ccm?_[to_keep_current_in_computing_skills]',
       'what_motivated_you_to_seek_a_computing_class_at_ccm?_[career_advancement]',
       'what_motivated_you_to_seek_a_computing_class_at_ccm?_[career_change]',
       'what_motivated_you_to_seek_a_computing_class_at_ccm?_[professional_development]',
       'what_motivated_you_to_seek_a_computing_class_at_ccm?_[job_displacement]',
       'what_motivated_you_to_seek_a_computing_class_at_ccm?_[relocation]',
       'what_motivated_you_to_seek_a_computing_class_at_ccm?_[it_industry_certifications]',
       'what_motivated_you_to_seek_a_computing_class_at_ccm?_[financial]',
       'what_motivated_you_to_seek_a_computing_class_at_ccm?_[personal_enrichment]',
       'what_motivated_you_to_seek_a_computing_class_at_ccm?_[curiosity]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[open_house]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[instant_decision_day]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[on-campus_information_session]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[titan's_tuesday_virtual_information_session]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[women_who_dare]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[regional_college_fair]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[middle/high_school_computing_class]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[middle/high_school_computing_related_club]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[computing-related_competitions_(e.g.,_robotics_competition,_lego_competition,_cybersecurity,_programming)]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[afterschool_computing-related_camp/program]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[summer_computing_related_camp/program]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[an_ap_computing_class]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[a_dual_enrollment_computing_class]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[family_or_friend_influence]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[family_or_friend_working_in_the_computing_field]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[high_school_teacher_or_guidance_counselor]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[employer_influence]',
       'how_did_you_hear_about_county_college_of_morris__[ccm_web_site]',
       'how_did_you_hear_about_county_college_of_morris__[billboard]',
       'how_did_you_hear_about_county_college_of_morris__[television]',
       'how_did_you_hear_about_county_college_of_morris__[radio]',
       'how_did_you_hear_about_county_college_of_morris__[social_media]',
       'how_did_you_hear_about_county_college_of_morris__[community_event]',
       'how_did_you_hear_about_county_college_of_morris__[family_member_or_friend]',
       'how_did_you_hear_about_county_college_of_morris__[employer]',
       'how_did_you_hear_about_county_college_of_morris__[current_student]',
       'how_did_you_hear_about_county_college_of_morris__[alumni]',
       'how_did_you_hear_about_county_college_of_morris__[high_school]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[affordable_cost]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[location/convenience]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[choice_of_programs]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[online_offerings]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[family/friend_referral]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[faculty/staff]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[college_reputation]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[scholarships]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[transfer_student]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[small_class_sizes]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[extra_curricula_opportunities]',
       'what_degree_program_are_you_currently_enrolled_in?',
       'did_you_receive_information_about_our_computing_course_from_any_of_the_following_sources?_[high_school_guidance_counselor]',
       'did_you_receive_information_about_our_computing_course_from_any_of_the_following_sources?_[ccm_information_technologies_website]',
       'did_you_receive_information_about_our_computing_course_from_any_of_the_following_sources?_[ccm_admissions]',
       'did_you_receive_information_about_our_computing_course_from_any_of_the_following_sources?_[ccm_advisor/counselor]',
       'did_you_receive_information_about_our_computing_course_from_any_of_the_following_sources?_[employer]',
       'did_you_receive_information_about_our_computing_course_from_any_of_the_following_sources?_[other]',
       'on_a_scale_of_1_to_5,_with_1_being_not_at_all_interested_and_5_being_extremely_interested,_how_interested_are_you_taking_more_courses_in_computer_science,_information_technology_or_game_development?',
       'if_you_answered_that_you_were_interested_in_taking_more_computing_classes,_which_ones_interest_you_most?_[web_development]',
       'if_you_answered_that_you_were_interested_in_taking_more_computing_classes,_which_ones_interest_you_most?_[cybersecurity]',

## 7 Clean inconsistent values

Examine important categorical features such as major and race or ethnicity. Look for spelling differences, repeated categories, blank values, or categories that should reasonably be grouped.

Show value counts before and after each important change. Do not combine categories without explaining why.

In [64]:
majors_clean["which_course_are_you_enrolled_in?"].value_counts(dropna=False)

which_course_are_you_enrolled_in?
CMP 128 Computer Science I                      78
CMP 131 Fundamentals of Programming (Python)    64
CMP 130 Intro to IT                             20
CMP 120 Foundations of Information Security     11
Name: count, dtype: int64

In [65]:
non_majors_clean["which_course_are_you_currently_enrolled_in?"].value_counts(dropna=False)

which_course_are_you_currently_enrolled_in?
CMP 135 Computer Concepts with Applications     48
CMP 126 Computer Technology and Applications    42
CMP 101 Computer Information Literacy           28
Name: count, dtype: int64

### Value-cleaning decisions

Explain what you changed, what you did not change, and why.

since the categories are already grouped and unique, there is no need to change.

## 8 Compare the two surveys

Compare the majors and non-majors column names. Identify:

- Questions or features found in both surveys
- Similar questions with different wording
- Features found in only one survey

Use pandas for the comparison and summarize what you discover.

In [66]:
shared_dfs = majors_clean.columns.intersection(non_majors_clean.columns)

In [67]:
majors_only = majors_clean.columns.difference(non_majors_clean.columns)

In [68]:
non_majors_only = non_majors_clean.columns.difference(majors_clean.columns)

### Survey comparison

Explain the important similarities and differences between the two surveys.

## 9 Validate the cleaned DataFrames

Before saving, verify both cleaned DataFrames. Check their shape, columns, missing values, duplicate rows, data types, and important category values.

If you discover a problem, return to the appropriate cleaning section and correct it.

In [69]:
majors_clean.shape

(173, 88)

In [70]:
majors_clean.columns

Index(['timestamp', 'which_course_are_you_enrolled_in?',
       'how_did_you_hear_about_county_college_of_morris?_[ccm_web_site]',
       'how_did_you_hear_about_county_college_of_morris?_[social_media]',
       'how_did_you_hear_about_county_college_of_morris?_[community_event]',
       'how_did_you_hear_about_county_college_of_morris?_[family_member_or_friend]',
       'how_did_you_hear_about_county_college_of_morris?_[current_ccm_student]',
       'how_did_you_hear_about_county_college_of_morris?_[ccm_alumni]',
       'how_did_you_hear_about_county_college_of_morris?_[high_school_teacher]',
       'how_did_you_hear_about_county_college_of_morris?_[high_school_counselor]',
       'how_did_you_hear_about_county_college_of_morris?_[in-app_advertisement]',
       'how_did_you_hear_about_county_college_of_morris?_[employer]',
       'how_did_you_hear_about_county_college_of_morris?_[billboard]',
       'how_did_you_hear_about_county_college_of_morris?_[television]',
       'how_did_you_hear_about_county_college_of_morris?_[radio]',
       'how_did_you_hear_about_county_college_of_morris?_[other]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[affordable_cost]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[location/convenience]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[choice_of_programs]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[online_offerings]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[family/friend_referral]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[faculty/staff]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[college_reputation]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[financial_aid]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[scholarships]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[small_class_sizes]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[extra-curricular_opportunities]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[accepted_my_transfer_credits]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[negative_experience_at_another_college]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[nj_stars_program]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[ability_to_transfer_ccm_credits_to_a_4-year_school]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[get_college_credit_while_in_high_school]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[open_house]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[instant_decision_day]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[on-campus_information_session]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[titans_tuesday_(virtual)_information_session]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[women_who_dare]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[regional_college_fair]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[hs_sharetime_information_session]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[challenger_program]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[cybersecurity_information_protection_program_participation_]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[information_session_at_my_high_school]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[campus_visit_with_my_high_school]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[campus_visit_(individual)]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[workforce_development_class]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[corporate_training]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[teen_arts_festival]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[summer_camp_at_ccm]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[middle/high_school_computing_class]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[middle/high_school_computing_related_club]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[computing-related_competitions_(e.g.,_robotics_competition,_lego_competition,_cybersecurity,_programming)]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[afterschool_computing-related_camp/program]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[summer_computing_related_camp/program]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[an_ap_computing_class]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[a_dual_enrollment_computing_class]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[family_or_friend_influence]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[family_or_friend_working_in_the_computing_field]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[high_school_teacher_or_guidance_counselor]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[employer_influence]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[current_ccm_student]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[experience_at_work]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[other]',
       'what_degree_program_are_you_currently_enrolled_in?',
       'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[to_get_a_job_in_the_computing_field]',
       'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[transfer_to_bachelor's_level_program]',
       'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[transfer_credits_back_to_hs_degree_(sharetime,_challenger_program)]',
       'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[career_advancement]',
       'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[career_change]',
       'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[professional_development]',
       'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[job_displacement]',
       'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[relocation]',
       'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[to_keep_current_in_tech_industry]',
       'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[it_industry_certifications]',
       'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[financial]',
       'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[personal_enrichment]',
       'did_you_receive_information_about_the_ccm_computing_programs_from_any_of_the_following_sources?_[high_school_guidance_counselor]',
       'did_you_receive_information_about_the_ccm_computing_programs_from_any_of_the_following_sources?_[high_school_teacher]',
       'did_you_receive_information_about_the_ccm_computing_programs_from_any_of_the_following_sources?_[ccm_information_technologies_website]',
       'did_you_receive_information_about_the_ccm_computing_programs_from_any_of_the_following_sources?_[ccm_admissions]',
       'did_you_receive_information_about_the_ccm_computing_programs_from_any_of_the_following_sources?_[ccm_advisor/counselor]',
       'did_you_receive_information_about_the_ccm_computing_programs_from_any_of_the_following_sources?_[employer]',
       'did_you_receive_information_about_the_ccm_computing_programs_from_any_of_the_following_sources?_[ccm_workforce_development]',
       'did_you_receive_information_about_the_ccm_computing_programs_from_any_of_the_following_sources?_[nj_workforce_development_program]',
       'did_you_receive_information_about_the_ccm_computing_programs_from_any_of_the_following_sources?_[other]',
       'was_a_computing_major/certificate_your_first_choice,_or_did_you_change_majors_from_a_different_ccm_program?_if_you_changed_majors,_indicate_what_your_first_major_was.',
       'on_a_scale_of_1_to_5,_with_1_being_not_at_all_interested_and_5_being_extremely_interested,_how_interested_are_you_in_taking_more_computing_classes?',
       'please_explain_your_answer_to_the_question_above.__why_or_why_not_would_you_be_interested_in_taking_another_computing_class?',
       'Age '],
      dtype='str')

In [71]:
majors_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 173 entries, 0 to 172
Data columns (total 88 columns):
 #   Column                                                                                                                                                                                                                                                           Non-Null Count  Dtype
---  ------                                                                                                                                                                                                                                                           --------------  -----
 0   timestamp                                                                                                                                                                                                                                                        173 non-null    str
 1   which_course_are_you_enrolled_in?                                                                                                                                                                                                                                173 non-null    str
 2   how_did_you_hear_about_county_college_of_morris?_[ccm_web_site]                                                                                                                                                                                                  173 non-null    str
 3   how_did_you_hear_about_county_college_of_morris?_[social_media]                                                                                                                                                                                                  173 non-null    str
 4   how_did_you_hear_about_county_college_of_morris?_[community_event]                                                                                                                                                                                               173 non-null    str
 5   how_did_you_hear_about_county_college_of_morris?_[family_member_or_friend]                                                                                                                                                                                       173 non-null    str
 6   how_did_you_hear_about_county_college_of_morris?_[current_ccm_student]                                                                                                                                                                                           173 non-null    str
 7   how_did_you_hear_about_county_college_of_morris?_[ccm_alumni]                                                                                                                                                                                                    173 non-null    str
 8   how_did_you_hear_about_county_college_of_morris?_[high_school_teacher]                                                                                                                                                                                           173 non-null    str
 9   how_did_you_hear_about_county_college_of_morris?_[high_school_counselor]                                                                                                                                                                                         173 non-null    str
 10  how_did_you_hear_about_county_college_of_morris?_[in-app_advertisement]                                                                                                                                                                                          173 non-null    str
 11  how_did_you_hear_about_county_college_of_morris?_[employer]                                                                                                                                                                                                      173 non-null    str
 12  how_did_you_hear_about_county_college_of_morris?_[billboard]                                                                                                                                                                                                     173 non-null    str
 13  how_did_you_hear_about_county_college_of_morris?_[television]                                                                                                                                                                                                    173 non-null    str
 14  how_did_you_hear_about_county_college_of_morris?_[radio]                                                                                                                                                                                                         173 non-null    str
 15  how_did_you_hear_about_county_college_of_morris?_[other]                                                                                                                                                                                                         173 non-null    str
 16  to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[affordable_cost]                                                                                                                                                      146 non-null    str
 17  to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[location/convenience]                                                                                                                                                 164 non-null    str
 18  to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[choice_of_programs]                                                                                                                                                   163 non-null    str
 19  to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[online_offerings]                                                                                                                                                     148 non-null    str
 20  to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[family/friend_referral]                                                                                                                                               147 non-null    str
 21  to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[faculty/staff]                                                                                                                                                        143 non-null    str
 22  to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[college_reputation]                                                                                                                                                   151 non-null    str
 23  to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[financial_aid]                                                                                                                                                        137 non-null    str
 24  to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[scholarships]                                                                                                                                                         135 non-null    str
 25  to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[small_class_sizes]                                                                                                                                                    149 non-null    str
 26  to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[extra-curricular_opportunities]                                                                                                                                       146 non-null    str
 27  to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[accepted_my_transfer_credits]                                                                                                                                         125 non-null    str
 28  to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[negative_experience_at_another_college]                                                                                                                               113 non-null    str
 29  to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[nj_stars_program]                                                                                                                                                     113 non-null    str
 30  to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[ability_to_transfer_ccm_credits_to_a_4-year_school]                                                                                                                   158 non-null    str
 31  to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[get_college_credit_while_in_high_school]                                                                                                                              130 non-null    str
 32  prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[open_house]                                                   173 non-null    str
 33  prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[instant_decision_day]                                         173 non-null    str
 34  prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[on-campus_information_session]                                173 non-null    str
 35  prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[titans_tuesday_(virtual)_information_session]                 173 non-null    str
 36  prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[women_who_dare]                                               173 non-null    str
 37  prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[regional_college_fair]                                        173 non-null    str
 38  prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[hs_sharetime_information_session]                             173 non-null    str
 39  prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[challenger_program]                                           173 non-null    str
 40  prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[cybersecurity_information_protection_program_participation_]  173 non-null    str
 41  prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[information_session_at_my_high_school]                        173 non-null    str
 42  prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[campus_visit_with_my_high_school]                             173 non-null    str
 43  prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[campus_visit_(individual)]                                    173 non-null    str
 44  prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[workforce_development_class]                                  173 non-null    str
 45  prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[corporate_training]                                           173 non-null    str
 46  prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[teen_arts_festival]                                           173 non-null    str
 47  prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[summer_camp_at_ccm]                                           173 non-null    str
 48  to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[middle/high_school_computing_class]                                                                                                     143 non-null    str
 49  to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[middle/high_school_computing_related_club]                                                                                              125 non-null    str
 50  to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[computing-related_competitions_(e.g.,_robotics_competition,_lego_competition,_cybersecurity,_programming)]                              131 non-null    str
 51  to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[afterschool_computing-related_camp/program]                                                                                             120 non-null    str
 52  to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[summer_computing_related_camp/program]                                                                                                  118 non-null    str
 53  to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[an_ap_computing_class]                                                                                                                  121 non-null    str
 54  to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[a_dual_enrollment_computing_class]                                                                                                      120 non-null    str
 55  to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[family_or_friend_influence]                                                                                                             143 non-null    str
 56  to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[family_or_friend_working_in_the_computing_field]                                                                                        134 non-null    str
 57  to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[high_school_teacher_or_guidance_counselor]                                                                                              132 non-null    str
 58  to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[employer_influence]                                                                                                                     124 non-null    str
 59  to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[current_ccm_student]                                                                                                                    132 non-null    str
 60  to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[experience_at_work]                                                                                                                     131 non-null    str
 61  to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[other]                                                                                                                                  112 non-null    str
 62  what_degree_program_are_you_currently_enrolled_in?                                                                                                                                                                                                               173 non-null    str
 63  what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[to_get_a_job_in_the_computing_field]                                                                                                                                                         114 non-null    str
 64  what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[transfer_to_bachelor's_level_program]                                                                                                                                                        114 non-null    str
 65  what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[transfer_credits_back_to_hs_degree_(sharetime,_challenger_program)]                                                                                                                          114 non-null    str
 66  what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[career_advancement]                                                                                                                                                                          114 non-null    str
 67  what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[career_change]                                                                                                                                                                               114 non-null    str

In [72]:
majors_clean.isna().sum()

timestamp                                                                                                                                                                   0
which_course_are_you_enrolled_in?                                                                                                                                           0
how_did_you_hear_about_county_college_of_morris?_[ccm_web_site]                                                                                                             0
how_did_you_hear_about_county_college_of_morris?_[social_media]                                                                                                             0
how_did_you_hear_about_county_college_of_morris?_[community_event]                                                                                                          0
                                                                                                                                                                         ...
did_you_receive_information_about_the_ccm_computing_programs_from_any_of_the_following_sources?_[other]                                                                    59
was_a_computing_major/certificate_your_first_choice,_or_did_you_change_majors_from_a_different_ccm_program?_if_you_changed_majors,_indicate_what_your_first_major_was.     60
on_a_scale_of_1_to_5,_with_1_being_not_at_all_interested_and_5_being_extremely_interested,_how_interested_are_you_in_taking_more_computing_classes?                       114
please_explain_your_answer_to_the_question_above.__why_or_why_not_would_you_be_interested_in_taking_another_computing_class?                                              114
Age                                                                                                                                                                         0
Length: 88, dtype: int64

In [73]:
majors_clean.duplicated().sum()

np.int64(0)

In [74]:
majors_clean["which_course_are_you_enrolled_in?"].value_counts(dropna=False)

which_course_are_you_enrolled_in?
CMP 128 Computer Science I                      78
CMP 131 Fundamentals of Programming (Python)    64
CMP 130 Intro to IT                             20
CMP 120 Foundations of Information Security     11
Name: count, dtype: int64

In [75]:
non_majors_clean.shape
non_majors_clean.columns
non_majors_clean.info()
non_majors_clean.isna().sum()
non_majors_clean.duplicated().sum()
non_majors_clean["which_course_are_you_currently_enrolled_in?"].value_counts(dropna=False)

<class 'pandas.DataFrame'>
RangeIndex: 118 entries, 0 to 117
Data columns (total 69 columns):
 #   Column                                                                                                                                                                                                                                           Non-Null Count  Dtype
---  ------                                                                                                                                                                                                                                           --------------  -----
 0   timestamp                                                                                                                                                                                                                                        118 non-null    str
 1   which_course_are_you_currently_enrolled_in?                                                                                                                                                                                                      118 non-null    str
 2   what_motivated_you_to_seek_a_computing_class_at_ccm?_[itâ€™s_a_required_class_for_the_degree_iâ€™m_seeking]                                                                                                                                      118 non-null    str
 3   what_motivated_you_to_seek_a_computing_class_at_ccm?_[to_keep_current_in_computing_skills]                                                                                                                                                       118 non-null    str
 4   what_motivated_you_to_seek_a_computing_class_at_ccm?_[career_advancement]                                                                                                                                                                        118 non-null    str
 5   what_motivated_you_to_seek_a_computing_class_at_ccm?_[career_change]                                                                                                                                                                             118 non-null    str
 6   what_motivated_you_to_seek_a_computing_class_at_ccm?_[professional_development]                                                                                                                                                                  118 non-null    str
 7   what_motivated_you_to_seek_a_computing_class_at_ccm?_[job_displacement]                                                                                                                                                                          118 non-null    str
 8   what_motivated_you_to_seek_a_computing_class_at_ccm?_[relocation]                                                                                                                                                                                118 non-null    str
 9   what_motivated_you_to_seek_a_computing_class_at_ccm?_[it_industry_certifications]                                                                                                                                                                118 non-null    str
 10  what_motivated_you_to_seek_a_computing_class_at_ccm?_[financial]                                                                                                                                                                                 118 non-null    str
 11  what_motivated_you_to_seek_a_computing_class_at_ccm?_[personal_enrichment]                                                                                                                                                                       118 non-null    str
 12  what_motivated_you_to_seek_a_computing_class_at_ccm?_[curiosity]                                                                                                                                                                                 118 non-null    str
 13  prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[open_house]                                   118 non-null    str
 14  prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[instant_decision_day]                         118 non-null    str
 15  prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[on-campus_information_session]                118 non-null    str
 16  prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[titan's_tuesday_virtual_information_session]  118 non-null    str
 17  prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[women_who_dare]                               118 non-null    str
 18  prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[regional_college_fair]                        118 non-null    str
 19  to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[middle/high_school_computing_class]                                                                                     97 non-null     str
 20  to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[middle/high_school_computing_related_club]                                                                              83 non-null     str
 21  to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[computing-related_competitions_(e.g.,_robotics_competition,_lego_competition,_cybersecurity,_programming)]              80 non-null     str
 22  to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[afterschool_computing-related_camp/program]                                                                             79 non-null     str
 23  to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[summer_computing_related_camp/program]                                                                                  79 non-null     str
 24  to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[an_ap_computing_class]                                                                                                  79 non-null     str
 25  to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[a_dual_enrollment_computing_class]                                                                                      79 non-null     str
 26  to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[family_or_friend_influence]                                                                                             94 non-null     str
 27  to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[family_or_friend_working_in_the_computing_field]                                                                        91 non-null     str
 28  to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[high_school_teacher_or_guidance_counselor]                                                                              94 non-null     str
 29  to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[employer_influence]                                                                                                     92 non-null     str
 30  how_did_you_hear_about_county_college_of_morris__[ccm_web_site]                                                                                                                                                                                  118 non-null    str
 31  how_did_you_hear_about_county_college_of_morris__[billboard]                                                                                                                                                                                     118 non-null    str
 32  how_did_you_hear_about_county_college_of_morris__[television]                                                                                                                                                                                    118 non-null    str
 33  how_did_you_hear_about_county_college_of_morris__[radio]                                                                                                                                                                                         118 non-null    str
 34  how_did_you_hear_about_county_college_of_morris__[social_media]                                                                                                                                                                                  118 non-null    str
 35  how_did_you_hear_about_county_college_of_morris__[community_event]                                                                                                                                                                               118 non-null    str
 36  how_did_you_hear_about_county_college_of_morris__[family_member_or_friend]                                                                                                                                                                       118 non-null    str
 37  how_did_you_hear_about_county_college_of_morris__[employer]                                                                                                                                                                                      118 non-null    str
 38  how_did_you_hear_about_county_college_of_morris__[current_student]                                                                                                                                                                               118 non-null    str
 39  how_did_you_hear_about_county_college_of_morris__[alumni]                                                                                                                                                                                        118 non-null    str
 40  how_did_you_hear_about_county_college_of_morris__[high_school]                                                                                                                                                                                   118 non-null    str
 41  to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[affordable_cost]                                                                                                                                      116 non-null    str
 42  to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[location/convenience]                                                                                                                                 113 non-null    str
 43  to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[choice_of_programs]                                                                                                                                   108 non-null    str
 44  to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[online_offerings]                                                                                                                                     105 non-null    str
 45  to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[family/friend_referral]                                                                                                                               101 non-null    str
 46  to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[faculty/staff]                                                                                                                                        97 non-null     str
 47  to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[college_reputation]                                                                                                                                   107 non-null    str
 48  to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[scholarships]                                                                                                                                         100 non-null    str
 49  to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[transfer_student]                                                                                                                                     98 non-null     str
 50  to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[small_class_sizes]                                                                                                                                    106 non-null    str
 51  to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[extra_curricula_opportunities]                                                                                                                        102 non-null    str
 52  what_degree_program_are_you_currently_enrolled_in?                                                                                                                                                                                               118 non-null    str
 53  did_you_receive_information_about_our_computing_course_from_any_of_the_following_sources?_[high_school_guidance_counselor]                                                                                                                       118 non-null    str
 54  did_you_receive_information_about_our_computing_course_from_any_of_the_following_sources?_[ccm_information_technologies_website]                                                                                                                 118 non-null    str
 55  did_you_receive_information_about_our_computing_course_from_any_of_the_following_sources?_[ccm_admissions]                                                                                                                                       118 non-null    str
 56  did_you_receive_information_about_our_computing_course_from_any_of_the_following_sources?_[ccm_advisor/counselor]                                                                                                                                118 non-null    str
 57  did_you_receive_information_about_our_computing_course_from_any_of_the_following_sources?_[employer]                                                                                                                                             118 non-null    str
 58  did_you_receive_information_about_our_computing_course_from_any_of_the_following_sources?_[other]                                                                                                                                                118 non-null    str
 59  on_a_scale_of_1_to_5,_with_1_being_not_at_all_interested_and_5_being_extremely_interested,_how_interested_are_you_taking_more_courses_in_computer_science,_information_technology_or_game_development?                                           118 non-null    int64
 60  if_you_answered_that_you_were_interested_in_taking_more_computing_classes,_which_ones_interest_you_most?_[web_development]                                                                                                                       118 non-null    str
 61  if_you_answered_that_you_were_interested_in_taking_more_computing_classes,_which_ones_interest_you_most?_[cybersecurity]                                                                                                                         118 non-null    str
 62  if_you_answered_that_you_were_interested_in_taking_more_computing_classes,_which_ones_interest_you_most?_[app_development]                                                                                                                       118 non-null    str
 63  if_you_answered_that_you_were_interested_in_taking_more_computing_classes,_which_ones_interest_you_most?_[data_analytics]                                                                                                                        118 non-null    str
 64  if_you_answered_that_you_were_interested_in_taking_more_computing_classes,_which_ones_interest_you_most?_[machine_learning/artificial_intelligence]                                                                                              118 non-null    str
 65  if_you_answered_that_you_were_interested_in_taking_more_computing_classes,_which_ones_interest_you_most?_[computer_programming]                                                                                                                  118 non-null    str
 66  if_you_answered_that_you_were_interested_in_taking_more_computing_classes,_which_ones_interest_you_most?_[game_design]                                                                                                                           118 non-null    str
 67  if_you_answered_that_you_were_interested_in_taking_more_computing_classes,_which_ones_interest_you_most?_[hardware_installation_&_repair]                                                                                                        118 non-null    str
 68  Age                                                                                                                                                                                                                                              118 non-null    str
dtypes: int64(1), str(68)
memory usage: 63.7 KB

which_course_are_you_currently_enrolled_in?
CMP 135 Computer Concepts with Applications     48
CMP 126 Computer Technology and Applications    42
CMP 101 Computer Information Literacy           28
Name: count, dtype: int64

## 10 Save the cleaned datasets

Use pandas to save these two files in the `cleaned-data` folder without including the DataFrame index:

- `majors_survey_cleaned.csv`
- `nonmajors_survey_cleaned.csv`

In [76]:
majors_clean.to_csv("cleaned-data/majors_cleaned.csv", index=False)

In [77]:
non_majors_clean.to_csv("cleaned-data/non_majors_cleaned.csv", index=False)

## 11 Verify the saved files

Use pandas to read both cleaned CSV files back into new DataFrames. Confirm their shape and column names. This verifies that the files were saved correctly.

In [78]:
new_majors = pd.read_csv("cleaned-data/majors_cleaned.csv")

In [79]:
new_non_majors = pd.read_csv("cleaned-data/non_majors_cleaned.csv")

## 12 Final reflection

In your own words, answer the following:

1. What were the most important cleaning decisions?
2. How did the majors and non-majors surveys differ?
3. What information may have been lost during cleaning?
4. What limitations remain in the cleaned datasets?
5. How could the cleaned data support a future recruitment study?

1. Removing Race/Ethnicity and Gender
2. they slightly differed in wording, but were similar for the most part
3. race and gender entries, as well as the old column name data
4. The repeated questions for different outputs(How did you hear about the county college of morris)
5. it can help create an unbiased view of how students may want to get recruited in the future

## Final Check

Before submitting:

- Run all cells from top to bottom.
- Correct all errors.
- Make sure outputs are visible.
- Confirm that both cleaned CSV files exist.
- Complete `AI-Use-Report.md`.
- Commit and push the latest work to GitHub.